---
- name: init nextcloud database
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root }}"
    db: nextcloud
    collation: utf8_unicode_ci
    encoding: utf8
    state: present
  tags:
    - nextcloud

- name: create nextcloud user
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root }}"
    check_implicit_admin: yes
    name: nextcloud
    password: "{{ nextcloud_password }}"
    priv: 'nextcloud.*:ALL,GRANT'
    host: localhost
    state: present
  tags:
    - nextcloud
